INTENT_EXEMPLARS = {
    "smalltalk": [
        "안녕",
        "안녕하세요",
        "고마워",
        "감사합니다",
        "오케이",
        "알겠어",
        "자기소개 해줘",
        "너는 누구야",
        "무엇을 할 수 있어?",
        "네 역할이 뭐야",
        "너는 어떤 일을 도와줘?",
        "hello",
        "hi there",
        "thanks",
        "thank you",
        "got it",
        "introduce yourself",
        "who are you",
        "what can you do",
        "what is your role",
        "what can you help with",
    ],
    "direct_extraction": [
        "이 문서의 텍스트를 추출해줘",
        "이미지 안 글자만 읽어줘",
        "이 파일 원문만 보여줘",
        "OCR로 텍스트 뽑아줘",
        "이 이미지 안에 있는 글자 그대로 보여줘",
        "문구 그대로 보여줘",
        "이 스크린샷에 보이는 문구를 그대로 적어줘",
        "이미지 속 텍스트를 한 글자도 바꾸지 말고 보여줘",
        "extract the text from this file",
        "read the text in the image",
        "transcribe this page",
        "give me only the text",
        "show me exactly what text appears in this screenshot",
        "write out the exact words visible in this screenshot",
        "show the exact text from the uploaded image without summarizing it",
    ],
    "factual_lookup": [
        "제목은 무엇입니까?",
        "총 몇 개입니까?",
        "언제 추가되었나요?",
        "몇 장부터 시작합니까?",
        "이름은 무엇입니까?",
        "1931년에 정리된 기본교리는 몇 개였습니까?",
        "which chapter starts the eschatology section",
        "what is the title of chapter 5",
        "how many items are there",
        "when was it added",
        "what is the name of section 3",
    ],
    "article_lookup": [
        "제5조의 내용은 무엇입니까?",
        "제12조 제2항을 알려줘",
        "제3조부터 제5조까지 설명해줘",
        "제7조 제1항의 의미는?",
        "article 7",
        "section 3 clause 2",
        "what does article 5 say",
        "show me section 12",
    ],
    "summarization": [
        "이 문서를 요약해줘",
        "차례를 기준으로 전체 구조를 설명해줘",
        "문서 전체를 정리해줘",
        "핵심만 요약해줘",
        "문서 전체 흐름을 한 번에 설명해줘",
        "목차 기준으로 구조를 개괄해줘",
        "give me the big-picture flow of this document",
        "outline the structure of the uploaded documents",
        "summarize this document",
        "give me an overview of the file",
        "summarize the whole chapter",
        "what are the main points",
        "walk me through the whole document flow",
    ],
    "comparison": [
        "두 문서의 차이점을 비교해줘",
        "A와 B의 공통점과 차이점은?",
        "이 규정과 저 규정을 비교해줘",
        "제5조와 제7조의 차이는?",
        "제4조와 제5조는 어떻게 다릅니까?",
        "이 규정과 저 규정의 다른 점이 뭐야?",
        "두 문서가 어떻게 다른지 핵심만 말해줘",
        "how do these two policies differ",
        "compare article 3 and article 4",
        "compare these two documents",
        "what is the difference between article 5 and article 7",
        "compare the two guidelines",
        "show similarities and differences",
    ],
    "general_knowledge": [
        "RAG가 무엇인가요?",
        "임베딩이란 무엇입니까?",
        "트랜스포머 모델을 설명해줘",
        "벡터 검색이 뭐야",
        "벡터 검색이 왜 중요한가요?",
        "트랜스포머 모델이 뭔가요?",
        "임베딩하고 reranker 차이가 뭐야?",
        "what is a transformer model",
        "explain machine learning",
        "what is an embedding model",
        "how does retrieval augmented generation work",
        "explain retrieval augmented generation",
    ],
    "default": [
        "이 내용에 대해 알려줘",
        "설명해줘",
        "이 부분을 이해하고 싶어",
        "이 내용이 중요해?",
        "tell me more about this",
        "help me understand this topic",
        "can you explain this part",
        "what should I know about this",
    ],
}


INTENT_MIN_CONFIDENCE = {
    "smalltalk": 0.60,
    "direct_extraction": 0.60,
    "factual_lookup": 0.60,
    "article_lookup": 0.66,
    "summarization": 0.58,
    "comparison": 0.60,
    "general_knowledge": 0.58,
    "default": 0.58,
}
